#PBS -N salina_l_ata_64
#PBS -l nodes=8:ppn=9
#PBS -M ebrahim@rice.edu
#PBS -q parallel
#PBS -m bae
#PBS -V
#PBS -o /scratch/em24/
#PBS -e /scratch/em24/



#mpiexec -n 64 ~/ompqr/ompqr /scratch/em24/dict/salina_204x54129.txt /scratch/em24/ompo_salina/salina_204x54129 204 54129 100 100 400 1 0.1 1 1 1 0 54129


for l in  100 200 300 400 800 1200 1600 2000 2400
do
	echo "l=$l"
	
	mpiexec -n 64 ~/ompqr/ata /scratch/em24/ompo_salina/salina_204x54129x"$l"_D /scratch/em24/ompo_salina/salina_204x54129x"$l"_64 204 54129 $l 64 1 100 0 1
	mpiexec -n 32 ~/ompqr/ata /scratch/em24/ompo_salina/salina_204x54129x"$l"_D /scratch/em24/ompo_salina/salina_204x54129x"$l"_64 204 54129 $l 64 1 100 0 1
	#mpiexec -n 16 ~/ompqr/ata /scratch/em24/ompo_salina/salina_204x54129x"$l"_D /scratch/em24/ompo_salina/salina_204x54129x"$l"_64 204 54129 $l 64 1 100 0 1
	#mpiexec -n 8  ~/ompqr/ata /scratch/em24/ompo_salina/salina_204x54129x"$l"_D /scratch/em24/ompo_salina/salina_204x54129x"$l"_64 204 54129 $l 64 1 100 0 1
	#mpiexec -n 4  ~/ompqr/ata /scratch/em24/ompo_salina/salina_204x54129x"$l"_D /scratch/em24/ompo_salina/salina_204x54129x"$l"_64 204 54129 $l 64 1 100 0 1
	#mpiexec -n 2  ~/ompqr/ata /scratch/em24/ompo_salina/salina_204x54129x"$l"_D /scratch/em24/ompo_salina/salina_204x54129x"$l"_64 204 54129 $l 64 1 100 0 1
	#mpiexec -n 1  ~/ompqr/ata /scratch/em24/ompo_salina/salina_204x54129x"$l"_D /scratch/em24/ompo_salina/salina_204x54129x"$l"_64 204 54129 $l 64 1 100 0 1
  
done
